name: Quality Gate

on:
  workflow_call:

jobs:
  lint:
    name: Run Linter (Ruff)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install Poetry & Dependencies
        run: |
          pip install poetry
          poetry install --only dev --no-root

      - name: Run Ruff Check
        run: poetry run ruff check .
        
      - name: Run Ruff Format Check
        run: poetry run ruff format --check .

  test:
    name: Run Tests (Pytest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install Poetry & Dependencies
        run: |
          pip install poetry
          poetry install --with testing --no-root

      - name: Run Pytest
        env:
          DEBUG: "True"

        run: poetry run pytest

  run:
    name: Health check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install Poetry & Dependencies
        run: |
          pip install poetry
          poetry install --only main --no-root

      - name: Run Server and Check Ping
        env:
          DEBUG: "True"

        run: |
          poetry run python manage.py migrate --no-input
          poetry run python manage.py runserver 8000 &
          
          timeout 10 bash -c 'until curl -s http://127.0.0.1:8000/ping/ > /dev/null; do sleep 1; done'
          
          RESPONSE=$(curl -s http://127.0.0.1:8000/ping/)
          echo "Response: $RESPONSE"
          
          STATUS=$(echo "$RESPONSE" | jq -r .status)
          if [ "$STATUS" = "ok" ]; then
            echo "✅ Project is working."
            exit 0
          else
            echo "❌ unknown response."
            exit 1
          fi
